### ISSUE TITLE
seems like LiteServ crashed with cblite tests with commit 5041a4edbc on stable branch

### ISSUE THREAD

**Issue by andreibaranouski** [couchbase/couchbase-lite-ios#288]
I use the latest sync_gateway stable branch 8a87bd53ca
and stable couchbase-lite-ios 5041a4edbc

my test params:
LITESERV_PATH="/Users/andrei/couchbase_src/couchbase-lite-ios/build/Products/Debug/LiteServ"
SYNCGATE_PATH="/Users/andrei/couchbase_src/sync_gateway/bin/sync_gateway"

launch test: 
node tests/cbl-replication-mismatch.js

I see that liteServ terminated over time with the errors in the replication tests like:

```
not ok 507 failed to get db info from http://127.0.0.1:59851/mismatch-test-one
  ---
    file:   /Users/andrei/couchbase_src/cblite-tests/node_modules/coax/node_modules/hoax/lib/hoax-core.js
    line:   16
    column: 9
    stack:  
      - getCaller (/Users/andrei/couchbase_src/cblite-tests/node_modules/tap/lib/tap-assert.js:418:17)
      - assert (/Users/andrei/couchbase_src/cblite-tests/node_modules/tap/lib/tap-assert.js:21:16)
      - Function.fail (/Users/andrei/couchbase_src/cblite-tests/node_modules/tap/lib/tap-assert.js:95:10)
      - Test._testAssert [as fail] (/Users/andrei/couchbase_src/cblite-tests/node_modules/tap/lib/tap-test.js:87:16)
      - /Users/andrei/couchbase_src/cblite-tests/tests/common.js:717:19
      - Request._callback (/Users/andrei/couchbase_src/cblite-tests/node_modules/coax/node_modules/hoax/lib/hoax-core.js:16:9)
      - self.callback (/Users/andrei/couchbase_src/cblite-tests/node_modules/coax/node_modules/hoax/node_modules/request/main.js:122:22)
      - Request.EventEmitter.emit (events.js:95:17)
      - ClientRequest.self.clientErrorHandler (/Users/andrei/couchbase_src/cblite-tests/node_modules/coax/node_modules/hoax/node_modules/request/main.js:225:10)
      - ClientRequest.EventEmitter.emit (events.js:95:17)
  ...
```

I set sleep in test execution and tried to checked it manually. indeed, liteServ terminated not from tests

with the previous commit 8284a88849 there are no any issues

test logs for both runs: https://friendpaste.com/6YdeEC9FG0emf2jgWULUW6
